;; expect: 3 1 -3 -1 -3 1 3 -1
(display (quotient 10 3))
(display " ")
(display (remainder 10 3))
(display " ")
(display (quotient -10 3))
(display " ")
(display (remainder -10 3))
(display " ")
(display (quotient 10 -3))
(display " ")
(display (remainder 10 -3))
(display " ")
(display (quotient -10 -3))
(display " ")
(display (remainder -10 -3))
