;; expect: 7 -3 7 -3 7 -3 7 -3
(display (floor 7))
(display " ")
(display (floor -3))
(display " ")
(display (ceiling 7))
(display " ")
(display (ceiling -3))
(display " ")
(display (truncate 7))
(display " ")
(display (truncate -3))
(display " ")
(display (round 7))
(display " ")
(display (round -3))
