;; expect: 42 -7 #f 0 #f
(display (string->number "42"))
(display " ")
(display (string->number "-7"))
(display " ")
(display (string->number "abc"))
(display " ")
(display (string->number "0"))
(display " ")
(display (string->number ""))
