
;; wasi-dir: tests
;; expect: quote x quasiquote y unquote z unquote-splicing w
(call-with-input-file "data/quotes.txt"
  (lambda (port)
    ;; Read 'x → (quote x)
    (let ((q (read port)))
      (display (car q))
      (display " ")
      (display (car (cdr q))))
    (display " ")
    ;; Read `y → (quasiquote y)
    (let ((q (read port)))
      (display (car q))
      (display " ")
      (display (car (cdr q))))
    (display " ")
    ;; Read ,z → (unquote z)
    (let ((q (read port)))
      (display (car q))
      (display " ")
      (display (car (cdr q))))
    (display " ")
    ;; Read ,@w → (unquote-splicing w)
    (let ((q (read port)))
      (display (car q))
      (display " ")
      (display (car (cdr q))))
    (newline)))
