;; expect: 0 0 0 0 0 0 248 63
(let ((bv (make-bytevector 8)))
  (bytevector-f64-native-set! bv 0 1.5)
  (display (bytevector-u8-ref bv 0))
  (display " ")
  (display (bytevector-u8-ref bv 1))
  (display " ")
  (display (bytevector-u8-ref bv 2))
  (display " ")
  (display (bytevector-u8-ref bv 3))
  (display " ")
  (display (bytevector-u8-ref bv 4))
  (display " ")
  (display (bytevector-u8-ref bv 5))
  (display " ")
  (display (bytevector-u8-ref bv 6))
  (display " ")
  (display (bytevector-u8-ref bv 7)))
