;; expect: 111000111000101
(display (if (char-alphabetic? #\a) 1 0))
(display (if (char-alphabetic? #\Z) 1 0))
(display (if (char-alphabetic? #\m) 1 0))
(display (if (char-alphabetic? #\1) 1 0))
(display (if (char-alphabetic? #\space) 1 0))
(display (if (char-alphabetic? #\!) 1 0))
(display (if (char-numeric? #\0) 1 0))
(display (if (char-numeric? #\5) 1 0))
(display (if (char-numeric? #\9) 1 0))
(display (if (char-numeric? #\a) 1 0))
(display (if (char-numeric? #\space) 1 0))
(display (if (char-numeric? #\!) 1 0))
(display (if (char-whitespace? #\space) 1 0))
(display (if (char-whitespace? #\a) 1 0))
(display (if (char-whitespace? #\newline) 1 0))
