;; expect: 110100100110101
(display (if (char-ci=? #\a #\A) 1 0))
(display (if (char-ci=? #\a #\a) 1 0))
(display (if (char-ci=? #\a #\b) 1 0))
(display (if (char-ci<? #\a #\B) 1 0))
(display (if (char-ci<? #\A #\a) 1 0))
(display (if (char-ci<? #\b #\A) 1 0))
(display (if (char-ci>? #\b #\A) 1 0))
(display (if (char-ci>? #\A #\a) 1 0))
(display (if (char-ci>? #\a #\B) 1 0))
(display (if (char-ci<=? #\a #\A) 1 0))
(display (if (char-ci<=? #\a #\B) 1 0))
(display (if (char-ci<=? #\b #\A) 1 0))
(display (if (char-ci>=? #\a #\A) 1 0))
(display (if (char-ci>=? #\A #\b) 1 0))
(display (if (char-ci>=? #\b #\A) 1 0))
