;; expect: #t#f#f#t#t#t#f#t
(display (string<? "abc" "abd"))
(display (string<? "abd" "abc"))
(display (string<? "abc" "abc"))
(display (string<? "ab" "abc"))
(display (string>? "abd" "abc"))
(display (string<=? "abc" "abc"))
(display (string<=? "abd" "abc"))
(display (string>=? "abc" "abc"))
(newline)
