;; skip: true
;; expect:
;; expect: 20 passed, 0 failed

(define (string-hash s)
  (let ((len (string-length s)))
    (let loop ((i 0) (h 0))
      (if (>= i len) (bitwise-and h 63)
          (loop (+ i 1) (+ h (char->integer (string-ref s i))))))))
(define (make-string-ht) (make-vector 64 '()))
(define (string-ht-set! ht key val)
  (let ((idx (string-hash key)))
    (vector-set! ht idx (cons (cons key val) (vector-ref ht idx)))))
(define (string-ht-has? ht key)
  (let ((idx (string-hash key)))
    (let loop ((b (vector-ref ht idx)))
      (cond ((null? b) #f) ((string=? (caar b) key) #t) (else (loop (cdr b)))))))

(include "../src/compiler/wit.scm")

(define *pass* 0)
(define *fail* 0)
(define (check name expected actual)
  (if (equal? expected actual)
      (set! *pass* (+ *pass* 1))
      (begin
        (set! *fail* (+ *fail* 1))
        (display "FAIL: ") (display name) (newline)
        (display "  expected: ") (write expected) (newline)
        (display "  actual:   ") (write actual) (newline))))

(define (make-string-lexer str)
  (make-wit-lexer (open-input-string str) "<test>"))
(define (tokens-from str)
  (let ((lx (make-string-lexer str)))
    (let loop ((acc '()))
      (let ((tok (wit-next-token lx)))
        (if (equal? tok '(eof)) (reverse acc) (loop (cons tok acc)))))))

(check "tok: empty string" '() (tokens-from ""))
(check "tok: identifier" '((id "foo")) (tokens-from "foo"))
(check "tok: kebab-case id" '((id "my-thing")) (tokens-from "my-thing"))
(check "tok: keyword" '((keyword "func")) (tokens-from "func"))
(check "tok: escaped keyword" '((id "func")) (tokens-from "%func"))
(check "tok: integer" '((integer 42)) (tokens-from "42"))
(check "tok: arrow" '((arrow)) (tokens-from "->"))
(check "tok: punctuation"
       '((punct #\{) (punct #\}) (punct #\() (punct #\))
         (punct #\<) (punct #\>) (punct #\;) (punct #\,)
         (punct #\:) (punct #\=) (punct #\.) (punct #\*))
       (tokens-from "{}()<>;,:=.*"))
(check "tok: at sign" '((punct #\@) (id "since")) (tokens-from "@since"))
(check "tok: line comment" '((id "before") (id "after")) (tokens-from "before // comment\nafter"))
(check "tok: block comment" '((id "before") (id "after")) (tokens-from "before /* comment */ after"))
(check "tok: nested block comment" '((id "a") (id "b")) (tokens-from "a /* outer /* inner */ still comment */ b"))
(check "tok: slash punct" '((id "a") (punct #\/) (id "b")) (tokens-from "a / b"))
(check "tok: mixed tokens"
       '((keyword "func") (punct #\() (id "name") (punct #\:)
         (keyword "string") (punct #\)) (arrow) (keyword "bool"))
       (tokens-from "func(name: string) -> bool"))
(check "tok: all keywords"
       '((keyword "package") (keyword "world") (keyword "interface")
         (keyword "import") (keyword "export") (keyword "use")
         (keyword "type") (keyword "record") (keyword "variant")
         (keyword "enum") (keyword "flags") (keyword "resource")
         (keyword "func") (keyword "bool") (keyword "string")
         (keyword "u8") (keyword "u32") (keyword "s64") (keyword "f64")
         (keyword "list") (keyword "option") (keyword "result")
         (keyword "tuple") (keyword "borrow") (keyword "own"))
       (tokens-from "package world interface import export use type record variant enum flags resource func bool string u8 u32 s64 f64 list option result tuple borrow own"))

(let ((lx (make-string-lexer "a b c")))
  (check "peek: first" '(id "a") (wit-peek-token lx))
  (check "peek: same" '(id "a") (wit-peek-token lx))
  (check "next: peeked" '(id "a") (wit-next-token lx))
  (check "next: advances" '(id "b") (wit-next-token lx)))

(newline)
(display *pass*) (display " passed, ") (display *fail*) (display " failed") (newline)
(if (> *fail* 0) (exit 1))
